[package]
name = "cool_editor"
version = "0.1.0"
edition = "2021"

[dependencies.iced]
git = "https://github.com/iced-rs/iced.git"
rev = "refs/tags/text-editor"
features = ["debug"]

[dependencies.tokio]
version = "1.32"
features = ["fs"]

[dependencies.rfd]
version = "0.12"
